In [1]:
import numpy as np

In [8]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.hstack((a,b))
y=np.vstack((a,b))
print(x)
print(y)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
x=np.column_stack((a,b,c))
y=np.row_stack((a,b,c))
print(x)
print(y)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
