In [2]:
import numpy as np

In [15]:
a=np.array([1,2,3,4,3])
b=np.array([[1,2,3,4,3],[1,2,3,4,5]])

In [20]:
print("number of elements in array = ",a.size)
print("number of subarrays in array", a.ndim)
print("number of subarrays in array", b.ndim)
print("data type of array elements",a.dtype)
print("dimensions/axes of array",a.shape)
print("dimensions of array",b.shape)

number of elements in array =  5
number of subarrays in array 1
number of subarrays in array 2
data type of array elements int32
dimensions of array (5,)
dimensions of array (2, 5)
dimensions of array 4


In [22]:
a=np.array([1,2,3,4,3], dtype=str)
b=np.array([[1,2,3,4,3],[1,2,3,4,5]], dtype=complex)

In [24]:
print(a)
print(b)

['1' '2' '3' '4' '3']
[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 3.+0.j]
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]]


In [26]:
#Intrinsic creation
a=np.zeros((3))
b=np.ones((3,1))
#by default data type is float64

In [28]:
print(a)
print(b)

[0. 0. 0.]
[[1.]
 [1.]
 [1.]]


In [38]:
a=np.arange(10)
b=np.arange(4,10)
c=np.arange(0,10,3)
d=np.arange(8).reshape(2,4)

#inclusive range

In [39]:
print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[0 3 6 9]
[[0 1 2 3]
 [4 5 6 7]]


In [41]:
#random
print(np.random.random(3))
print(np.random.random((2,2)))

[0.83915823 0.66570691 0.48195503]
[[0.07539111 0.80674226]
 [0.46813374 0.91354587]]


In [44]:
a=np.array([1,2,3,4,5])
print(a+2)
print(a*2)
print(a^2)

b=np.array([1,2,3,4,6])
print(a+b)

[3 4 5 6 7]
[ 2  4  6  8 10]
[3 0 1 6 7]
[ 2  4  6  8 11]


In [47]:
#Matric Product
a=np.arange(9).reshape(3,3)
b=np.arange(10,1,-1).reshape(3,3)
print(np.dot(a,b))
#same
print(a.dot(b))

[[ 15  12   9]
 [ 78  66  54]
 [141 120  99]]


In [ ]:
#Universal Functions (ufunc)
'''
a function operating on an array in an 
element-by-element fashion. This means that it acts individually on each single element 
of the input array to generate a corresponding result in a new output array. In the end, 
you obtain an array of the same size as the input. 
sqrt()
log()
sin() ....
'''

In [49]:
#aggregate functions
print(np.arange(10).sum())
print(np.arange(10).min())
print(np.arange(10).max())
print(np.arange(10).mean())

45
0
9
4.5


In [54]:
#indexing and slincing
a=np.arange(10,20)
print(a[4:8])
print(a[0:9:3])
print(a[4])
print(a[-4])
print(a[[4,8,1]]) #can also select multiples

[14 15 16 17]
[10 13 16]
14
16
[14 18 11]


In [56]:
#matrix slicing
a=np.arange(9).reshape(3,3)
print(a[1,:])  #second row
print(a[:,0])  #first column

[3 4 5]
[0 3 6]


In [63]:
#iteration
a=np.arange(9).reshape(3,3)
for row in a:
    print (row)

for i in a.flat:
    print(i, end=" ")

[0 1 2]
[3 4 5]
[6 7 8]
0 1 2 3 4 5 6 7 8 

In [65]:
#boolean ararys
a=np.random.random((3,3))
a=a>0.5
print(a)

[[ True  True  True]
 [False False  True]
 [ True False  True]]


In [69]:
#2d array ro 1D
a=np.arange(4).reshape((2,2))
print(a)
a=a.ravel()
print(a)

[[0 1]
 [2 3]]
[0 1 2 3]
